$('#conner_r_t1').mouseenter(function(){
	$('#conner_r_t1>ul').css("display","block")
	$('#conner_r_t2>ul').css("display","none")
})
$('#conner_r_t2').mouseenter(function(){
	$(this).css("background","#FFFFFF")
	$('#conner_r_t2>ul').css("display","block")
	$('#conner_r_t1>ul').css("display","none")
})
$('#conner_r_m1').mouseenter(function(){
	$('#conner_r_m1>ul').css("display","block")
	$('#conner_r_m2>ul').css("display","none")
})
$('#conner_r_m2').mouseenter(function(){
	$(this).css("background","#FFFFFF")
	$('#conner_r_m2>ul').css("display","block")
	$('#conner_r_m1>ul').css("display","none")
})
$('#conner_r_m3').mouseenter(function(){
	$('#conner_r_m3>ul').css("display","block")
	$('#conner_r_m4>ul').css("display","none")
})
$('#conner_r_m4').mouseenter(function(){
	$(this).css("background","#FFFFFF")
	$('#conner_r_m4>ul').css("display","block")
	$('#conner_r_m3>ul').css("display","none")
})
$('#conner_r_m5').mouseenter(function(){
	$('#conner_r_m5>ul').css("display","block")
	$('#conner_r_m6>ul').css("display","none")
})
$('#conner_r_m6').mouseenter(function(){
	$(this).css("background","#FFFFFF")
	$('#conner_r_m6>ul').css("display","block")
	$('#conner_r_m5>ul').css("display","none")
})
$('#conner_r_b1').mouseenter(function(){
	$('#conner_r_b1>ul').css("display","block")
	$('#conner_r_b2>ul').css("display","none")
})
$('#conner_r_b2').mouseenter(function(){
	$(this).css("background","#FFFFFF")
	$('#conner_r_b2>ul').css("display","block")
	$('#conner_r_b1>ul').css("display","none")
})
